import Head from "next/head";
import clsx from "clsx";
import { WrapperProps, BasicLayoutProps } from "types/props";
import { SITE_CLASSNAME, SITE_TITLE } from "config/site";

const HomeLayout = ({ title, children }: BasicLayoutProps) => {
  return (
    <div className={clsx(SITE_CLASSNAME)}>
      <Head>
        <title>{title || SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </div>
  );
};

export default HomeLayout;
